package com.tarikusta.spacesurvivors.player;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/** Every SQL statement that touches {@code player_profile}. */
@Repository
public class PlayerRepository {

    private final JdbcClient db;

    public PlayerRepository(JdbcClient db) {
        this.db = db;
    }

    /** The player this device belongs to, or empty if the device has never been seen. */
    public Optional<UUID> findIdByDevice(String deviceId) {
        return db.sql("SELECT player_id FROM player_profile WHERE device_id = :device")
                .param("device", deviceId)
                .query(UUID.class)
                .optional();
    }

    /**
     * Create the player. {@code player_id} is generated by the database default, so
     * {@code RETURNING} is how we learn it without a second round trip.
     *
     * @throws org.springframework.dao.DuplicateKeyException if the device or the name is taken
     */
    public UUID insert(String deviceId, String displayName, String ip) {
        return db.sql("""
                        INSERT INTO player_profile (device_id, display_name, last_ip)
                        VALUES (:device, :name, CAST(:ip AS inet))
                        RETURNING player_id
                        """)
                .param("device", deviceId)
                .param("name", displayName)
                .param("ip", ip)
                .query(UUID.class)
                .single();
    }

    /** Record that we just saw this player. {@code updated_at} is stamped by the trigger. */
    public void touch(UUID playerId, String ip) {
        db.sql("UPDATE player_profile SET last_ip = CAST(:ip AS inet) WHERE player_id = :id")
                .param("id", playerId)
                .param("ip", ip)
                .update();
    }

    /**
     * Change the display name.
     *
     * <p>No "is this name free?" check first: between the check and the write another
     * request could take it. The unique index is the real guard, so we simply write and
     * let the constraint reject a clash.</p>
     *
     * @throws org.springframework.dao.DuplicateKeyException if the name is already taken
     * @return true if the player exists and was renamed
     */
    public boolean rename(UUID playerId, String displayName) {
        return db.sql("UPDATE player_profile SET display_name = :name WHERE player_id = :id")
                .param("id", playerId)
                .param("name", displayName)
                .update() == 1;
    }

    public Optional<PlayerRow> find(UUID playerId) {
        return db.sql("""
                        SELECT player_id, device_id, display_name, country,
                               host(last_ip) AS last_ip, first_login_date, updated_at
                          FROM player_profile
                         WHERE player_id = :id
                        """)
                .param("id", playerId)
                .query((rs, rowNum) -> new PlayerRow(
                        rs.getObject("player_id", UUID.class),
                        rs.getString("device_id"),
                        rs.getString("display_name"),
                        rs.getString("country"),
                        rs.getString("last_ip")))
                .optional();
    }

    public record PlayerRow(UUID playerId, String deviceId, String displayName,
                            String country, String lastIp) {
    }
}
