package com.tarikusta.spacesurvivors.player;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * The {@code player_profile} row: who a player is.
 *
 * <p>{@code player_id} is generated by the database, not by Hibernate — the column has
 * {@code DEFAULT gen_random_uuid()} and {@code @GeneratedValue} tells JPA to read the
 * value back after the insert rather than supply one. Keeping generation in the database
 * means every writer gets the same rule, including migrations and manual SQL.</p>
 */
@Entity
@Table(name = "player_profile")
public class PlayerProfile {

    @Id
    @GeneratedValue
    @Column(name = "player_id", updatable = false)
    private UUID playerId;

    @Column(name = "device_id", nullable = false, updatable = false)
    private String deviceId;

    @Column(name = "display_name", nullable = false)
    private String displayName;

    @Column
    private String country;

    /**
     * Postgres' {@code inet} type has no JPA equivalent, so it is declared explicitly and
     * carried as text. Hibernate would otherwise bind a varchar and Postgres would refuse
     * the comparison; {@code columnDefinition} also keeps {@code ddl-auto=validate} happy.
     * The value is already validated to be a literal address before it reaches here.
     */
    @Column(name = "last_ip", columnDefinition = "inet")
    private String lastIp;

    /** Set once by the database default and never touched again. */
    @Column(name = "first_login_date", insertable = false, updatable = false)
    private Instant firstLoginDate;

    /** Written by a trigger on every update, so JPA reads it and never sends it. */
    @Column(name = "updated_at", insertable = false, updatable = false)
    private Instant updatedAt;

    protected PlayerProfile() {
        // JPA needs a no-arg constructor.
    }

    public PlayerProfile(String deviceId, String displayName, String lastIp) {
        this.deviceId = deviceId;
        this.displayName = displayName;
        this.lastIp = lastIp;
    }


    /**
     * Identity is the primary key, and nothing else.
     *
     * <p>JPA needs these to be stable: the persistence context uses them to recognise an
     * instance it already holds, and a {@code Set} of entities silently misbehaves without
     * them. Comparing mutable fields instead would mean an entity changed identity the
     * moment someone edited it.</p>
     *
     * <p>{@code hashCode} is a constant rather than {@code id.hashCode()} on purpose: it
     * has to stay the same across an entity's whole life, including before an id exists.
     * A collection would otherwise lose an element the instant it was persisted.</p>
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof PlayerProfile that)) {
            return false;
        }
        return playerId != null && Objects.equals(playerId, that.playerId);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    public UUID getPlayerId() {
        return playerId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getCountry() {
        return country;
    }

    public String getLastIp() {
        return lastIp;
    }

    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /** The shape the rest of the application works with. */
    public Player toPlayer() {
        return new Player(playerId, deviceId, displayName, country);
    }
}
