package com.tarikusta.spacesurvivors.player;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * The {@code player_profile} row: who a player is.
 *
 * <p>{@code player_id} is generated by the database, not by Hibernate — the column has
 * {@code DEFAULT gen_random_uuid()} and {@code @GeneratedValue} tells JPA to read the
 * value back after the insert rather than supply one. Keeping generation in the database
 * means every writer gets the same rule, including migrations and manual SQL.</p>
 */
@Entity
@Table(name = "player_profile")
public class PlayerProfile {

    @Id
    @GeneratedValue
    @Column(name = "player_id", updatable = false)
    private UUID playerId;

    @Column(name = "device_id", nullable = false, updatable = false)
    private String deviceId;

    @Column(name = "display_name", nullable = false)
    private String displayName;

    @Column
    private String country;

    /**
     * Read-only to JPA, and it has to be.
     *
     * <p>Postgres' {@code inet} has no JPA type. Hibernate binds a {@code String} as
     * {@code varchar}, and Postgres refuses to assign varchar to an inet column — so any
     * update Hibernate wrote for this entity failed outright, whatever the update was
     * actually changing. {@code columnDefinition} does not help: it only shapes generated
     * DDL, and Flyway owns the schema here.</p>
     *
     * <p>Nothing is lost by making it read-only, because JPA never had a reason to write
     * it: the address is set by {@link PlayerProfileRepository#insertIfFree} and refreshed
     * by {@link PlayerProfileRepository#touch}, both of which cast it explicitly in SQL.</p>
     */
    @Column(name = "last_ip", columnDefinition = "inet", insertable = false, updatable = false)
    private String lastIp;

    /**
     * BCrypt hash of the device's secret — the thing that finally makes an identity claim
     * checkable. Never the secret itself: a copy of this table has to be worthless, and
     * BCrypt is deliberately slow and salted per row so that a stolen one stays that way.
     *
     * <p>Null for rows created before V2. Those devices adopt a secret the first time they
     * authenticate; refusing them instead would have locked existing players out of their
     * own progress.</p>
     */
    @Column(name = "device_secret_hash")
    private String deviceSecretHash;

    /** Set once by the database default and never touched again. */
    @Column(name = "first_login_date", insertable = false, updatable = false)
    private Instant firstLoginDate;

    /** Written by a trigger on every update, so JPA reads it and never sends it. */
    @Column(name = "updated_at", insertable = false, updatable = false)
    private Instant updatedAt;

    protected PlayerProfile() {
        // JPA needs a no-arg constructor.
    }

    public PlayerProfile(String deviceId, String displayName, String lastIp) {
        this.deviceId = deviceId;
        this.displayName = displayName;
        this.lastIp = lastIp;
    }

    /**
     * Identity is the primary key, and nothing else.
     *
     * <p>JPA needs these to be stable: the persistence context uses them to recognise an
     * instance it already holds, and a {@code Set} of entities silently misbehaves without
     * them. Comparing mutable fields instead would mean an entity changed identity the
     * moment someone edited it.</p>
     *
     * <p>{@code hashCode} is a constant rather than {@code id.hashCode()} on purpose: it
     * has to stay the same across an entity's whole life, including before an id exists.
     * A collection would otherwise lose an element the instant it was persisted.</p>
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof PlayerProfile that)) {
            return false;
        }
        return playerId != null && Objects.equals(playerId, that.playerId);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    public UUID getPlayerId() {
        return playerId;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDeviceSecretHash() {
        return deviceSecretHash;
    }

    public void setDeviceSecretHash(String deviceSecretHash) {
        this.deviceSecretHash = deviceSecretHash;
    }

    public String getCountry() {
        return country;
    }

    public String getLastIp() {
        return lastIp;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /** The shape the rest of the application works with. */
    public Player toPlayer() {
        return new Player(playerId, deviceId, displayName, country, firstLoginDate);
    }
}
