package com.tarikusta.spacesurvivors.player;

import com.tarikusta.spacesurvivors.auth.Caller;
import com.tarikusta.spacesurvivors.domain.AlreadyTakenException;
import com.tarikusta.spacesurvivors.domain.InvalidInputException;
import com.tarikusta.spacesurvivors.domain.NotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;
import org.springframework.dao.DataIntegrityViolationException;

import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class PlayerServiceTest {

    private static final Caller CALLER = new Caller("dev-abc", "127.0.0.1");
    private static final UUID EXISTING = UUID.randomUUID();
    private static final UUID CREATED = UUID.randomUUID();

    private PlayerProfileRepository players;
    private PlayerService service;

    /**
     * player_id is generated by the database, so a real PlayerProfile cannot be built with
     * a known one. Mocking the entity keeps that generation rule where it belongs instead
     * of opening a setter purely for tests.
     *
     * <p>Always assign the result to a variable before using it: this method stubs, and
     * Mockito refuses a stubbing opened inside another one's argument list.</p>
     */
    private static PlayerProfile profileWithId(UUID id) {
        PlayerProfile profile = Mockito.mock(PlayerProfile.class);
        when(profile.getPlayerId()).thenReturn(id);
        return profile;
    }

    @BeforeEach
    void setUp() {
        players = Mockito.mock(PlayerProfileRepository.class);
        service = new PlayerService(players);
    }

    @Nested
    @DisplayName("resolving a caller")
    class Resolve {

        @Test
        void reusesTheProfileWhenTheDeviceIsKnown() {
            PlayerProfile known = profileWithId(EXISTING);
            when(players.findByDeviceId("dev-abc")).thenReturn(Optional.of(known));

            assertThat(service.resolveOrCreate(CALLER)).isEqualTo(EXISTING);

            verify(players).touch(EXISTING, "127.0.0.1");
            verify(players, never()).insertIfFree(anyString(), anyString(), anyString());
        }

        @Test
        void createsAProfileTheFirstTimeADeviceAppears() {
            PlayerProfile created = profileWithId(CREATED);
            when(players.findByDeviceId("dev-abc"))
                    .thenReturn(Optional.empty())
                    .thenReturn(Optional.of(created));
            when(players.insertIfFree(eq("dev-abc"), anyString(), eq("127.0.0.1"))).thenReturn(1);

            assertThat(service.resolveOrCreate(CALLER)).isEqualTo(CREATED);
        }

        @Test
        void generatesASixDigitDefaultNameThatPassesTheNameRules() {
            PlayerProfile created = profileWithId(CREATED);
            when(players.findByDeviceId(anyString()))
                    .thenReturn(Optional.empty())
                    .thenReturn(Optional.of(created));
            when(players.insertIfFree(anyString(), anyString(), anyString())).thenReturn(1);

            service.resolveOrCreate(CALLER);

            ArgumentCaptor<String> name = ArgumentCaptor.forClass(String.class);
            verify(players).insertIfFree(anyString(), name.capture(), anyString());
            assertThat(name.getValue()).matches("User\\d{6}");
        }
    }

    @Nested
    @DisplayName("first contact races")
    class Races {

        /**
         * The regression that mattered: this used to be handled by catching
         * DuplicateKeyException, which cannot work inside a transaction because a raised
         * constraint violation aborts it. The insert must therefore report a clash by
         * returning nothing.
         */
        @Test
        void adoptsThePlayerCreatedByAConcurrentRequestForTheSameDevice() {
            PlayerProfile theirs = profileWithId(EXISTING);
            when(players.findByDeviceId("dev-abc"))
                    .thenReturn(Optional.empty())            // nothing there when we looked
                    .thenReturn(Optional.of(theirs));        // someone inserted while we tried
            when(players.insertIfFree(anyString(), anyString(), anyString())).thenReturn(0);

            assertThat(service.resolveOrCreate(CALLER)).isEqualTo(EXISTING);
        }

        @Test
        void triesAnotherNameWhenTheGeneratedOneIsTaken() {
            PlayerProfile created = profileWithId(CREATED);
            when(players.findByDeviceId("dev-abc"))
                    .thenReturn(Optional.empty())        // before the first attempt
                    .thenReturn(Optional.empty())        // that name was taken
                    .thenReturn(Optional.of(created));   // the next one was free
            when(players.insertIfFree(anyString(), anyString(), anyString()))
                    .thenReturn(0)
                    .thenReturn(1);

            assertThat(service.resolveOrCreate(CALLER)).isEqualTo(CREATED);

            ArgumentCaptor<String> names = ArgumentCaptor.forClass(String.class);
            verify(players, Mockito.times(2)).insertIfFree(anyString(), names.capture(), anyString());
            assertThat(names.getAllValues()).doesNotHaveDuplicates();
        }

        @Test
        void givesUpRatherThanLoopingForeverIfEveryNameClashes() {
            when(players.findByDeviceId("dev-abc")).thenReturn(Optional.empty());
            when(players.insertIfFree(anyString(), anyString(), anyString())).thenReturn(0);

            assertThatThrownBy(() -> service.resolveOrCreate(CALLER))
                    .isInstanceOf(IllegalStateException.class);
        }
    }

    @Nested
    @DisplayName("choosing a name")
    class Rename {

        private PlayerProfile stored;

        @BeforeEach
        void deviceIsKnown() {
            stored = Mockito.mock(PlayerProfile.class);
            when(stored.getPlayerId()).thenReturn(EXISTING);
            when(players.findByDeviceId("dev-abc")).thenReturn(Optional.of(stored));
            when(players.findById(EXISTING)).thenReturn(Optional.of(stored));
        }

        @ParameterizedTest
        @ValueSource(strings = { "abc", "Tarik", "Kaptan_42", "_", "aaaaaaaaaaaaaaaa" })
        void acceptsNamesWithinTheRules(String name) {
            if (name.length() < 3) return;   // "_" is covered by the too-short case below
            when(stored.toPlayer()).thenReturn(new Player(EXISTING, "dev-abc", name, null));

            assertThat(service.rename(CALLER, name).displayName()).isEqualTo(name);
            verify(stored).setDisplayName(name);
        }

        @ParameterizedTest
        @ValueSource(strings = { "ab", "a", "aaaaaaaaaaaaaaaaa" })
        void rejectsNamesOfTheWrongLength(String name) {
            assertThatThrownBy(() -> service.rename(CALLER, name))
                    .isInstanceOf(InvalidInputException.class)
                    .hasMessageContaining("characters");
        }

        @ParameterizedTest
        @ValueSource(strings = { "Tarik Usta", "tarik!", "ali-veli", "emoji😀", "nokta." })
        void rejectsNamesWithDisallowedCharacters(String name) {
            assertThatThrownBy(() -> service.rename(CALLER, name))
                    .isInstanceOf(InvalidInputException.class);
        }

        @Test
        void trimsBeforeJudgingAndBeforeStoring() {
            when(stored.toPlayer()).thenReturn(new Player(EXISTING, "dev-abc", "Tarik", null));

            service.rename(CALLER, "   Tarik   ");

            verify(stored).setDisplayName("Tarik");
        }

        @Test
        void reportsAClashRatherThanOverwritingSomeoneElse() {
            when(players.saveAndFlush(any())).thenThrow(new DataIntegrityViolationException("unique"));

            assertThatThrownBy(() -> service.rename(CALLER, "Tarik"))
                    .isInstanceOf(AlreadyTakenException.class);
        }

        @Test
        void reportsAMissingPlayerRatherThanClaimingSuccess() {
            when(players.findById(EXISTING)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> service.rename(CALLER, "Tarik"))
                    .isInstanceOf(NotFoundException.class);
        }

        @Test
        void rejectsNull() {
            assertThatThrownBy(() -> service.rename(CALLER, null))
                    .isInstanceOf(InvalidInputException.class);
        }
    }
}
