package com.tarikusta.spacesurvivors.player;

import com.tarikusta.spacesurvivors.domain.AlreadyTakenException;
import com.tarikusta.spacesurvivors.domain.AuthenticationFailedException;
import com.tarikusta.spacesurvivors.domain.InvalidInputException;
import com.tarikusta.spacesurvivors.domain.NotFoundException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class PlayerServiceTest {

    private static final String DEVICE = "dev-abc";
    private static final String SECRET = "a-secret-long-enough-to-be-worth-something";
    private static final String IP = "127.0.0.1";
    private static final UUID EXISTING = UUID.randomUUID();
    private static final UUID CREATED = UUID.randomUUID();

    private PlayerProfileRepository players;
    private PasswordEncoder passwordEncoder;
    private PlayerService service;

    @BeforeEach
    void setUp() {
        players = Mockito.mock(PlayerProfileRepository.class);
        // The real encoder, not a mock: hashing is the point of these tests, and BCrypt's
        // own matches() is what decides whether a device is let in.
        passwordEncoder = new BCryptPasswordEncoder();
        service = new PlayerService(players, passwordEncoder);
    }

    /**
     * player_id is generated by the database, so a real PlayerProfile cannot be built with
     * a known one. Mocking the entity keeps that generation rule where it belongs instead
     * of opening a setter purely for tests.
     *
     * <p>Always assign the result to a variable before using it: this method stubs, and
     * Mockito refuses a stubbing opened inside another one's argument list.</p>
     */
    private PlayerProfile profile(UUID id, String secretHash) {
        PlayerProfile profile = Mockito.mock(PlayerProfile.class);
        when(profile.getPlayerId()).thenReturn(id);
        when(profile.getDeviceSecretHash()).thenReturn(secretHash);
        return profile;
    }

    @Nested
    @DisplayName("authenticating a device")
    class Authenticate {

        @Test
        @DisplayName("an unknown device is registered rather than refused")
        void registersOnFirstContact() {
            PlayerProfile created = profile(CREATED, null);
            when(players.findByDeviceId(DEVICE))
                    .thenReturn(Optional.empty())
                    .thenReturn(Optional.of(created));
            when(players.insertIfFree(eq(DEVICE), anyString(), eq(IP), anyString())).thenReturn(1);

            assertThat(service.authenticateDevice(DEVICE, SECRET, IP)).isEqualTo(CREATED);
        }

        @Test
        @DisplayName("the secret is stored hashed, never as itself")
        void hashesTheSecretBeforeStoringIt() {
            PlayerProfile created = profile(CREATED, null);
            when(players.findByDeviceId(DEVICE))
                    .thenReturn(Optional.empty())
                    .thenReturn(Optional.of(created));
            when(players.insertIfFree(anyString(), anyString(), any(), anyString())).thenReturn(1);

            service.authenticateDevice(DEVICE, SECRET, IP);

            ArgumentCaptor<String> stored = ArgumentCaptor.forClass(String.class);
            verify(players).insertIfFree(anyString(), anyString(), any(), stored.capture());
            assertThat(stored.getValue()).isNotEqualTo(SECRET).startsWith("$2");
            assertThat(passwordEncoder.matches(SECRET, stored.getValue())).isTrue();
        }

        @Test
        void letsAKnownDeviceInWithTheRightSecret() {
            PlayerProfile known = profile(EXISTING, passwordEncoder.encode(SECRET));
            when(players.findByDeviceId(DEVICE)).thenReturn(Optional.of(known));

            assertThat(service.authenticateDevice(DEVICE, SECRET, IP)).isEqualTo(EXISTING);
            verify(players).touch(EXISTING, IP);
        }

        @Test
        @DisplayName("a wrong secret is refused and nothing is recorded")
        void refusesAWrongSecret() {
            PlayerProfile known = profile(EXISTING, passwordEncoder.encode(SECRET));
            when(players.findByDeviceId(DEVICE)).thenReturn(Optional.of(known));

            assertThatThrownBy(() -> service.authenticateDevice(DEVICE, "not-the-right-secret-at-all", IP))
                    .isInstanceOf(AuthenticationFailedException.class);
            verify(players, never()).touch(any(), anyString());
        }

        @Test
        @DisplayName("the refusal never says which half was wrong")
        void doesNotRevealWhetherTheDeviceIsKnown() {
            PlayerProfile known = profile(EXISTING, passwordEncoder.encode(SECRET));
            when(players.findByDeviceId(DEVICE)).thenReturn(Optional.of(known));

            // Distinguishing "no such device" from "wrong secret" would let someone
            // enumerate accounts one request at a time.
            assertThatThrownBy(() -> service.authenticateDevice(DEVICE, "wrong-secret-here-padded-out", IP))
                    .hasMessageNotContainingAny("secret is wrong", "unknown device", DEVICE);
        }

        @Test
        @DisplayName("a device registered before V2 adopts the secret it presents")
        void adoptsASecretForAPreV2Device() {
            PlayerProfile legacy = profile(EXISTING, null);
            when(players.findByDeviceId(DEVICE)).thenReturn(Optional.of(legacy));

            // Refusing these would lock existing players out of progress they already earned.
            assertThat(service.authenticateDevice(DEVICE, SECRET, IP)).isEqualTo(EXISTING);
            verify(legacy).setDeviceSecretHash(anyString());
            verify(players).saveAndFlush(legacy);
        }
    }

    @Nested
    @DisplayName("first contact races")
    class Races {

        /**
         * The regression that mattered: this used to be handled by catching
         * DuplicateKeyException, which cannot work inside a transaction because a raised
         * constraint violation aborts it. The insert reports a clash by returning nothing.
         */
        @Test
        void adoptsThePlayerCreatedByAConcurrentRequestForTheSameDevice() {
            PlayerProfile theirs = profile(EXISTING, null);
            when(players.findByDeviceId(DEVICE))
                    .thenReturn(Optional.empty())        // nothing there when we looked
                    .thenReturn(Optional.of(theirs));    // someone inserted while we tried
            when(players.insertIfFree(anyString(), anyString(), any(), anyString())).thenReturn(0);

            assertThat(service.authenticateDevice(DEVICE, SECRET, IP)).isEqualTo(EXISTING);
        }

        @Test
        void triesAnotherNameWhenTheGeneratedOneIsTaken() {
            PlayerProfile created = profile(CREATED, null);
            when(players.findByDeviceId(DEVICE))
                    .thenReturn(Optional.empty())        // before the first attempt
                    .thenReturn(Optional.empty())        // that name was taken
                    .thenReturn(Optional.of(created));   // the next one was free
            when(players.insertIfFree(anyString(), anyString(), any(), anyString()))
                    .thenReturn(0)
                    .thenReturn(1);

            assertThat(service.authenticateDevice(DEVICE, SECRET, IP)).isEqualTo(CREATED);

            ArgumentCaptor<String> names = ArgumentCaptor.forClass(String.class);
            verify(players, Mockito.times(2)).insertIfFree(anyString(), names.capture(), any(), anyString());
            assertThat(names.getAllValues()).doesNotHaveDuplicates();
        }

        @Test
        void givesUpRatherThanLoopingForeverIfEveryNameClashes() {
            when(players.findByDeviceId(DEVICE)).thenReturn(Optional.empty());
            when(players.insertIfFree(anyString(), anyString(), any(), anyString())).thenReturn(0);

            assertThatThrownBy(() -> service.authenticateDevice(DEVICE, SECRET, IP))
                    .isInstanceOf(IllegalStateException.class);
        }

        @Test
        void generatesASixDigitDefaultName() {
            PlayerProfile created = profile(CREATED, null);
            when(players.findByDeviceId(anyString()))
                    .thenReturn(Optional.empty())
                    .thenReturn(Optional.of(created));
            when(players.insertIfFree(anyString(), anyString(), any(), anyString())).thenReturn(1);

            service.authenticateDevice(DEVICE, SECRET, IP);

            ArgumentCaptor<String> name = ArgumentCaptor.forClass(String.class);
            verify(players).insertIfFree(anyString(), name.capture(), any(), anyString());
            assertThat(name.getValue()).matches("User\\d{6}");
        }
    }

    @Nested
    @DisplayName("choosing a name")
    class Rename {

        private PlayerProfile stored;

        @BeforeEach
        void playerExists() {
            stored = Mockito.mock(PlayerProfile.class);
            when(players.findById(EXISTING)).thenReturn(Optional.of(stored));
        }

        @ParameterizedTest
        @ValueSource(strings = { "abc", "Tarik", "Kaptan_42", "aaaaaaaaaaaaaaaa" })
        void acceptsNamesWithinTheRules(String name) {
            when(stored.toPlayer()).thenReturn(new Player(EXISTING, DEVICE, name, null));

            assertThat(service.rename(EXISTING, name).displayName()).isEqualTo(name);
            verify(stored).setDisplayName(name);
        }

        @ParameterizedTest
        @ValueSource(strings = { "ab", "a", "aaaaaaaaaaaaaaaaa" })
        void rejectsNamesOfTheWrongLength(String name) {
            assertThatThrownBy(() -> service.rename(EXISTING, name))
                    .isInstanceOf(InvalidInputException.class)
                    .hasMessageContaining("characters");
        }

        @ParameterizedTest
        @ValueSource(strings = { "Tarik Usta", "tarik!", "ali-veli", "emoji😀", "nokta." })
        void rejectsNamesWithDisallowedCharacters(String name) {
            assertThatThrownBy(() -> service.rename(EXISTING, name))
                    .isInstanceOf(InvalidInputException.class);
        }

        @Test
        void trimsBeforeJudgingAndBeforeStoring() {
            when(stored.toPlayer()).thenReturn(new Player(EXISTING, DEVICE, "Tarik", null));

            service.rename(EXISTING, "   Tarik   ");

            verify(stored).setDisplayName("Tarik");
        }

        @Test
        void reportsAClashRatherThanOverwritingSomeoneElse() {
            when(players.saveAndFlush(any())).thenThrow(new DataIntegrityViolationException("unique"));

            assertThatThrownBy(() -> service.rename(EXISTING, "Tarik"))
                    .isInstanceOf(AlreadyTakenException.class);
        }

        @Test
        void reportsAMissingPlayerRatherThanClaimingSuccess() {
            when(players.findById(EXISTING)).thenReturn(Optional.empty());

            assertThatThrownBy(() -> service.rename(EXISTING, "Tarik"))
                    .isInstanceOf(NotFoundException.class);
        }

        @Test
        void rejectsNull() {
            assertThatThrownBy(() -> service.rename(EXISTING, null))
                    .isInstanceOf(InvalidInputException.class);
        }
    }
}
