#!/usr/bin/env bash
#
# Creates everything the service needs to run in Azure, once. Run it after `az login`.
#
# It is idempotent: every step checks whether the thing already exists, so re-running after
# a failure picks up where it stopped instead of erroring or building a second copy. That
# matters more than it sounds — the first run of something like this rarely finishes.
#
# What it builds, and why these choices:
#
#   Container Apps, not App Service. It scales to zero: with no players connected the
#   compute bill is nothing, and a cold start is a few seconds. For a game whose traffic is
#   "Tarik and some friends" that is the difference between pennies and a monthly charge.
#
#   ghcr.io, not Azure Container Registry. ACR's cheapest tier is a flat ~$5/month for
#   somewhere to keep an image. GitHub's registry comes with the repository at no cost. The
#   image stays private and the container app is given a read-only token to pull it.
#
#   Postgres Flexible Server, Burstable B1ms — the smallest that exists. Covered by the
#   12-month free allowance on a new subscription; roughly $13-15/month after that.
#
# Nothing here prints a secret. The two the app needs (the database password and the JWT
# signing key) are generated locally, handed to Azure as container-app secrets, and written
# to deploy/.env.azure — which is git-ignored — so that a later run of this script or a
# manual `az` command can find them again.

set -euo pipefail

# ── settings ──────────────────────────────────────────────────────────────
LOCATION="${LOCATION:-westeurope}"
RG="${RG:-spacesurvivors-rg}"
PG_SERVER="${PG_SERVER:-spacesurvivors-pg-$RANDOM}"   # must be globally unique
PG_ADMIN="${PG_ADMIN:-ssadmin}"
PG_DB="spacesurvivors"
ENVIRONMENT="${ENVIRONMENT:-spacesurvivors-env}"
APP="${APP:-spacesurvivors-api}"
IMAGE="${IMAGE:-ghcr.io/tarikustaa/spacesurvivors-backend:latest}"

SECRETS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.env.azure"

say() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }

# ── preflight ─────────────────────────────────────────────────────────────
command -v az >/dev/null || { echo "az CLI not found — install it first."; exit 1; }
az account show >/dev/null 2>&1 || { echo "Not logged in. Run: az login"; exit 1; }

say "Subscription"
az account show --query '{name:name, id:id}' -o tsv

# The two resource providers this uses are not registered on a brand-new subscription, and
# the failure when they are not is an opaque one — so ask for them up front.
say "Registering resource providers (safe to repeat, may take a minute)"
az provider register --namespace Microsoft.App --wait
az provider register --namespace Microsoft.DBforPostgreSQL --wait
az provider register --namespace Microsoft.OperationalInsights --wait

# ── secrets ───────────────────────────────────────────────────────────────
# Reuse what a previous run generated; only invent them once. Re-generating the JWT key
# would invalidate every token already issued, and re-generating the database password
# would not match the server that already exists.
if [[ -f "$SECRETS_FILE" ]]; then
    say "Reusing secrets from $SECRETS_FILE"
    # shellcheck disable=SC1090
    source "$SECRETS_FILE"
else
    say "Generating secrets → $SECRETS_FILE"
    # LC_ALL=C because tr on a UTF-8 locale rejects the byte stream from /dev/urandom.
    DB_PASSWORD="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)"
    JWT_SECRET="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64)"
    umask 077
    cat > "$SECRETS_FILE" <<EOF
# Generated by azure-setup.sh — git-ignored, never commit.
DB_PASSWORD='$DB_PASSWORD'
JWT_SECRET='$JWT_SECRET'
PG_SERVER='$PG_SERVER'
EOF
fi

# ── resource group ────────────────────────────────────────────────────────
say "Resource group: $RG"
az group create --name "$RG" --location "$LOCATION" -o none

# ── postgres ──────────────────────────────────────────────────────────────
if az postgres flexible-server show -g "$RG" -n "$PG_SERVER" >/dev/null 2>&1; then
    say "Postgres server $PG_SERVER already exists"
else
    say "Creating Postgres $PG_SERVER (several minutes)"
    az postgres flexible-server create \
        --resource-group "$RG" \
        --name "$PG_SERVER" \
        --location "$LOCATION" \
        --admin-user "$PG_ADMIN" \
        --admin-password "$DB_PASSWORD" \
        --tier Burstable \
        --sku-name Standard_B1ms \
        --storage-size 32 \
        --version 16 \
        --public-access 0.0.0.0 \
        --yes -o none
fi

# 0.0.0.0-0.0.0.0 is Azure's special rule meaning "other Azure services", not "the whole
# internet" — the container app's outbound address is not fixed, so it cannot be listed.
# Everything still needs the password and TLS. Narrowing this to a private VNet is the
# proper answer and costs more; noted rather than done.
say "Firewall rule for Azure-internal callers"
az postgres flexible-server firewall-rule create \
    --resource-group "$RG" --name "$PG_SERVER" \
    --rule-name allow-azure-services \
    --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 -o none 2>/dev/null || true

say "Database $PG_DB"
az postgres flexible-server db create \
    --resource-group "$RG" --server-name "$PG_SERVER" --database-name "$PG_DB" -o none 2>/dev/null || true

PG_HOST="$(az postgres flexible-server show -g "$RG" -n "$PG_SERVER" --query fullyQualifiedDomainName -o tsv)"
# sslmode=require: Azure refuses an unencrypted connection anyway, and being explicit means
# the driver fails with a clear message rather than a handshake error if that ever changes.
DB_URL="jdbc:postgresql://${PG_HOST}:5432/${PG_DB}?sslmode=require"

# ── container apps ────────────────────────────────────────────────────────
az extension add --name containerapp --upgrade --only-show-errors -o none

if az containerapp env show -g "$RG" -n "$ENVIRONMENT" >/dev/null 2>&1; then
    say "Container Apps environment $ENVIRONMENT already exists"
else
    say "Creating Container Apps environment $ENVIRONMENT"
    az containerapp env create -g "$RG" -n "$ENVIRONMENT" --location "$LOCATION" -o none
fi

echo
echo "The image is private, so the container app needs a token that can read it."
echo "Create one at https://github.com/settings/tokens with the single scope read:packages"
read -r -p "GitHub username: " GH_USER
read -r -s -p "GitHub token (read:packages): " GH_TOKEN; echo

if az containerapp show -g "$RG" -n "$APP" >/dev/null 2>&1; then
    say "Updating existing container app $APP"
    az containerapp registry set -g "$RG" -n "$APP" \
        --server ghcr.io --username "$GH_USER" --password "$GH_TOKEN" -o none
    az containerapp secret set -g "$RG" -n "$APP" \
        --secrets db-password="$DB_PASSWORD" jwt-secret="$JWT_SECRET" -o none
    az containerapp update -g "$RG" -n "$APP" --image "$IMAGE" -o none
else
    say "Creating container app $APP"
    az containerapp create \
        --resource-group "$RG" \
        --name "$APP" \
        --environment "$ENVIRONMENT" \
        --image "$IMAGE" \
        --registry-server ghcr.io \
        --registry-username "$GH_USER" \
        --registry-password "$GH_TOKEN" \
        --target-port 8080 \
        --ingress external \
        --secrets db-password="$DB_PASSWORD" jwt-secret="$JWT_SECRET" \
        --env-vars \
            DB_URL="$DB_URL" \
            DB_USER="$PG_ADMIN" \
            DB_PASSWORD=secretref:db-password \
            JWT_SECRET=secretref:jwt-secret \
        --cpu 0.5 --memory 1.0Gi \
        --min-replicas 0 --max-replicas 2 \
        -o none
fi

FQDN="$(az containerapp show -g "$RG" -n "$APP" --query properties.configuration.ingress.fqdn -o tsv)"

say "Done"
cat <<EOF

  API           https://${FQDN}
  Health        https://${FQDN}/health
  Postgres      ${PG_HOST}
  Secrets       ${SECRETS_FILE}  (git-ignored)

Next:
  1. curl https://${FQDN}/health          → {"status":"UP","db":"UP"}
  2. Point Unity's BackendConfig.DefaultBaseUrl at https://${FQDN}
  3. Add these GitHub repository secrets so CI can deploy on every green push:
       AZURE_CREDENTIALS   (see deploy/README.md)
       AZURE_RG=${RG}
       AZURE_APP=${APP}

If /health says db is DOWN, the first request also had to run Flyway against an empty
database — give it a few seconds and ask again before assuming something is wrong.
EOF
