-- V1__init.sql — SpaceSurvivors backend schema.
-- Flyway applies this once on first startup and records it in flyway_schema_history.
-- Never edit a migration that has already run; add a V2__ file instead.

-- ── player_profile ──────────────────────────────────────────────────────────
-- Who the player is. One row per player, created the first time a device is seen.
--
--   player_id  is the identity. Generated here, never changes, and everything
--              else in the schema hangs off it.
--   device_id  is how we recognise them. Generated by the client, stored on the
--              device, and replaceable — a reinstall or a new phone produces a
--              new one. Keeping the two apart is what will later let a real
--              login attach several devices to one player without losing progress.
--
-- uuid rather than a sequence: a sequential id would leak how many players exist.
CREATE TABLE player_profile (
    player_id        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id        text        NOT NULL UNIQUE,
    display_name     text        NOT NULL
                                 CHECK (char_length(display_name) BETWEEN 3 AND 16)
                                 CHECK (display_name ~ '^[A-Za-z0-9_]+$'),
    country          text,       -- ISO-3166 alpha-2; NULL until a GeoIP source exists
    last_ip          inet,       -- Postgres' native IP type. Personal data: see Memory_bank.
    first_login_date timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()   -- doubles as "last seen"
);

-- Display names are unique CASE-INSENSITIVELY. A plain UNIQUE would let "tarik"
-- and "TARIK" coexist, which makes impersonation trivial. Indexing the lowered
-- value enforces it while still storing whatever capitalisation the player chose.
CREATE UNIQUE INDEX player_profile_display_name_key
    ON player_profile (lower(display_name));

-- ── player_progress ─────────────────────────────────────────────────────────
-- What the player has achieved: the cloud save. The entire client PlayerProfile
-- is stored as ONE json object in progress_data (jsonb = Postgres' binary,
-- indexable JSON). The client owns that shape; the server stores it as-is and
-- never unpacks it, so the game can add fields without a migration.
--
--   version = optimistic lock. The client sends the version it last read on PUT;
--   the UPDATE runs WHERE version = :v. Zero rows changed means someone else
--   wrote first => 409 Conflict, and the client merges and retries.
--
-- One row per player: this is the current state, not a history. (An append-only
-- run log was considered and deliberately deferred — see Memory_bank.)
CREATE TABLE player_progress (
    player_id     uuid        PRIMARY KEY REFERENCES player_profile(player_id) ON DELETE CASCADE,
    progress_data jsonb       NOT NULL,
    version       integer     NOT NULL DEFAULT 1,
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ── leaderboard ─────────────────────────────────────────────────────────────
-- One row per (player, mode) = that player's personal best. POST /v1/leaderboard
-- upserts here only when a run beats the stored best.
--   mode = 'infinite' | 'campaign'
CREATE TABLE leaderboard (
    player_id        uuid        NOT NULL REFERENCES player_profile(player_id) ON DELETE CASCADE,
    mode             text        NOT NULL,
    survived_seconds real        NOT NULL CHECK (survived_seconds >= 0),
    kills            integer     NOT NULL CHECK (kills >= 0),
    reached_level    integer     NOT NULL CHECK (reached_level >= 1),
    bosses_defeated  integer     NOT NULL CHECK (bosses_defeated >= 0),
    achieved_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (player_id, mode)
);

-- Board reads are "top N by survived_seconds within a mode" — index that.
CREATE INDEX leaderboard_by_mode_seconds
    ON leaderboard (mode, survived_seconds DESC);

-- ── updated_at ──────────────────────────────────────────────────────────────
-- Kept honest by the database rather than trusting every code path to set it.
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER player_profile_touch_updated_at
    BEFORE UPDATE ON player_profile
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER player_progress_touch_updated_at
    BEFORE UPDATE ON player_progress
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
