-- V3__admin_user.sql — the people who administer the game, as opposed to the people who play it.
--
-- This is a second, completely separate identity system, and the separation is the whole
-- point of the table rather than an implementation detail:
--
--   player_profile  is a DEVICE. It authenticates with a secret the game generated by
--                   itself, it is created automatically the first time it is seen, and
--                   nobody ever chose its name or its password. There are as many rows as
--                   there are installations.
--
--   admin_user      is a PERSON. It is created deliberately, it authenticates with a
--                   password that person chose and typed, and it holds a browser session
--                   rather than a token. There will be one or two rows, ever.
--
-- Keeping them in one table with a "role" column would have meant one compromise reaching
-- both: every player row would sit one boolean away from administrator, and the endpoint
-- that auto-creates players would be one bug away from creating one. They also want
-- opposite defaults — a player is created on sight, an admin never is.
--
-- No row is inserted here. A migration that seeds an administrator has to carry that
-- account's password hash in the repository, and a hash in a public repository is a
-- password everyone has: BCrypt slows an attacker down, it does not stop one who can take
-- the hash home. The first account is created at startup from the environment instead —
-- see admin/AdminBootstrap.
CREATE TABLE admin_user (
    admin_id      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    username      text        NOT NULL
                              CHECK (char_length(username) BETWEEN 3 AND 32),

    -- BCrypt, never the password. Same reasoning as player_profile.device_secret_hash:
    -- a copy of this table has to be worthless on its own.
    password_hash text        NOT NULL,

    -- Spring Security wants authorities named "ROLE_ADMIN"; the prefix is its convention,
    -- not information, so the column stores "ADMIN" and the prefix is added when the row is
    -- turned into a UserDetails. Storing the prefix here would bake a framework's naming
    -- into the data.
    role          text        NOT NULL DEFAULT 'ADMIN',

    -- A way to revoke access without deleting the row and losing who did what. Disabling
    -- is reversible and auditable; DELETE is neither.
    enabled       boolean     NOT NULL DEFAULT true,

    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

-- Case-insensitive uniqueness, exactly as player_profile.display_name has it. Without this
-- "admin" and "Admin" would be two accounts, which is a foothold rather than a feature:
-- the person reading a log cannot tell them apart, and neither can the person who thought
-- they had disabled one of them.
CREATE UNIQUE INDEX admin_user_username_key ON admin_user (lower(username));

COMMENT ON TABLE admin_user IS
    'Backoffice operators. Separate from player_profile on purpose: a person with a chosen '
    'password and a browser session, not a device with a generated secret and a token.';
